-- Skema MySQL/MariaDB Sineverse Cinema
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS pengguna (
 id INT AUTO_INCREMENT PRIMARY KEY,nama VARCHAR(150) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,no_hp VARCHAR(30) DEFAULT '',role ENUM('customer','admin','kasir','manajer') NOT NULL,status ENUM('aktif','banned') NOT NULL DEFAULT 'aktif',foto VARCHAR(255) DEFAULT '',email_terverifikasi TINYINT(1) NOT NULL DEFAULT 1,poin INT NOT NULL DEFAULT 0,cabang_id INT DEFAULT 1,hak_akses VARCHAR(255) DEFAULT '',dibuat_pada DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS studio (
 id INT AUTO_INCREMENT PRIMARY KEY,nama VARCHAR(100) NOT NULL,tipe VARCHAR(30) NOT NULL DEFAULT '2D',jumlah_baris INT NOT NULL DEFAULT 6,jumlah_kolom INT NOT NULL DEFAULT 10,cabang_id INT DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS kursi (
 id INT AUTO_INCREMENT PRIMARY KEY,studio_id INT NOT NULL,baris VARCHAR(5) NOT NULL,nomor INT NOT NULL,tipe VARCHAR(30) NOT NULL DEFAULT 'reguler',UNIQUE KEY ux_kursi(studio_id,baris,nomor),FOREIGN KEY(studio_id) REFERENCES studio(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS film (
 id INT AUTO_INCREMENT PRIMARY KEY,judul VARCHAR(190) NOT NULL,genre VARCHAR(150) NOT NULL,durasi INT NOT NULL DEFAULT 100,sinopsis TEXT,poster_warna VARCHAR(20) DEFAULT '#7c5cff',rating DECIMAL(3,1) DEFAULT 0,status VARCHAR(30) NOT NULL DEFAULT 'tayang',harga_dasar INT NOT NULL DEFAULT 35000,tmdb_id INT DEFAULT NULL,poster_url TEXT,trailer_key VARCHAR(100) DEFAULT '',bahasa VARCHAR(60) DEFAULT 'Indonesia',rating_usia VARCHAR(20) DEFAULT 'SU',dibuat_pada DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS jadwal (
 id INT AUTO_INCREMENT PRIMARY KEY,film_id INT NOT NULL,studio_id INT NOT NULL,tanggal DATE NOT NULL,jam TIME NOT NULL,selesai_pada VARCHAR(30) DEFAULT '',FOREIGN KEY(film_id) REFERENCES film(id),FOREIGN KEY(studio_id) REFERENCES studio(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS promo (
 id INT AUTO_INCREMENT PRIMARY KEY,kode VARCHAR(100) NOT NULL UNIQUE,deskripsi TEXT,diskon_persen INT NOT NULL DEFAULT 10,berlaku_hingga DATE NOT NULL,aktif TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS tiket (
 id INT AUTO_INCREMENT PRIMARY KEY,kode_tiket VARCHAR(100) NOT NULL UNIQUE,jadwal_id INT NOT NULL,customer_id INT,kasir_id INT,kursi_ids TEXT NOT NULL,total_harga INT NOT NULL,metode_bayar VARCHAR(50) NOT NULL,role_pemesan VARCHAR(20) DEFAULT '',subtotal_harga INT NOT NULL DEFAULT 0,diskon_jabatan_persen INT NOT NULL DEFAULT 0,potongan_jabatan INT NOT NULL DEFAULT 0,kode_promo VARCHAR(100) DEFAULT '',potongan_promo INT NOT NULL DEFAULT 0,poin_digunakan INT NOT NULL DEFAULT 0,potongan_poin INT NOT NULL DEFAULT 0,total_produk INT NOT NULL DEFAULT 0,refund_status VARCHAR(30) DEFAULT '',status VARCHAR(30) NOT NULL DEFAULT 'pending',kode_qr TEXT,dibuat_pada DATETIME DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(jadwal_id) REFERENCES jadwal(id),FOREIGN KEY(customer_id) REFERENCES pengguna(id),FOREIGN KEY(kasir_id) REFERENCES pengguna(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS pembayaran (
 id INT AUTO_INCREMENT PRIMARY KEY,tiket_id INT NOT NULL,kode_transaksi VARCHAR(100) NOT NULL UNIQUE,jumlah INT NOT NULL,metode VARCHAR(50) NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'menunggu',dibuat_pada DATETIME DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(tiket_id) REFERENCES tiket(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ulasan (
 id INT AUTO_INCREMENT PRIMARY KEY,film_id INT NOT NULL,customer_id INT NOT NULL,rating INT NOT NULL DEFAULT 5,komentar TEXT,terverifikasi TINYINT(1) NOT NULL DEFAULT 0,dibuat_pada DATETIME DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(film_id) REFERENCES film(id),FOREIGN KEY(customer_id) REFERENCES pengguna(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cabang (id INT AUTO_INCREMENT PRIMARY KEY,nama VARCHAR(150) NOT NULL,kota VARCHAR(100) NOT NULL,alamat TEXT,fasilitas TEXT,aktif TINYINT(1) NOT NULL DEFAULT 1) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS pengaturan_sistem (kunci VARCHAR(100) PRIMARY KEY,nilai TEXT NOT NULL,keterangan TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS audit_log (id INT AUTO_INCREMENT PRIMARY KEY,pengguna_id INT,aksi VARCHAR(100) NOT NULL,entitas VARCHAR(100) DEFAULT '',entitas_id INT,detail TEXT,ip_address VARCHAR(45) DEFAULT '',dibuat_pada DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS login_attempt (id INT AUTO_INCREMENT PRIMARY KEY,email VARCHAR(190) NOT NULL,ip_address VARCHAR(45) NOT NULL,berhasil TINYINT(1) NOT NULL DEFAULT 0,dibuat_pada DATETIME DEFAULT CURRENT_TIMESTAMP,INDEX idx_login_attempt(email,ip_address,dibuat_pada)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS verifikasi_email (pengguna_id INT PRIMARY KEY,kode VARCHAR(20) NOT NULL,kedaluwarsa_pada DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS reset_password (id INT AUTO_INCREMENT PRIMARY KEY,pengguna_id INT NOT NULL,token VARCHAR(190) NOT NULL UNIQUE,kedaluwarsa_pada DATETIME NOT NULL,digunakan TINYINT(1) NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS reservasi_kursi (id INT AUTO_INCREMENT PRIMARY KEY,pengguna_id INT NOT NULL,jadwal_id INT NOT NULL,kursi_id INT NOT NULL,token VARCHAR(190) NOT NULL,kedaluwarsa_pada DATETIME NOT NULL,UNIQUE KEY ux_reservasi(jadwal_id,kursi_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS detail_tiket (id INT AUTO_INCREMENT PRIMARY KEY,tiket_id INT NOT NULL,jadwal_id INT,kursi_id INT NOT NULL,harga INT NOT NULL,UNIQUE KEY ux_detail(tiket_id,kursi_id),UNIQUE KEY ux_detail_jadwal(jadwal_id,kursi_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS refund (id INT AUTO_INCREMENT PRIMARY KEY,tiket_id INT NOT NULL UNIQUE,pengguna_id INT NOT NULL,jumlah INT NOT NULL,persentase INT NOT NULL,alasan TEXT,status VARCHAR(30) NOT NULL DEFAULT 'diproses',dibuat_pada DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS favorit (pengguna_id INT NOT NULL,film_id INT NOT NULL,dibuat_pada DATETIME DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(pengguna_id,film_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS notifikasi (id INT AUTO_INCREMENT PRIMARY KEY,pengguna_id INT NOT NULL,judul VARCHAR(190) NOT NULL,pesan TEXT NOT NULL,tautan VARCHAR(255) DEFAULT '',channel VARCHAR(100) DEFAULT 'aplikasi,email,whatsapp',dibaca TINYINT(1) NOT NULL DEFAULT 0,dibuat_pada DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS poin_transaksi (id INT AUTO_INCREMENT PRIMARY KEY,pengguna_id INT NOT NULL,tiket_id INT,tipe VARCHAR(30) NOT NULL,jumlah INT NOT NULL,keterangan TEXT,dibuat_pada DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS produk (id INT AUTO_INCREMENT PRIMARY KEY,nama VARCHAR(150) NOT NULL,kategori VARCHAR(50) NOT NULL DEFAULT 'makanan',harga INT NOT NULL,stok INT NOT NULL DEFAULT 0,aktif TINYINT(1) NOT NULL DEFAULT 1,gambar VARCHAR(255) DEFAULT '') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS pesanan_produk (id INT AUTO_INCREMENT PRIMARY KEY,tiket_id INT NOT NULL,produk_id INT NOT NULL,jumlah INT NOT NULL,harga_satuan INT NOT NULL,ukuran VARCHAR(20) NOT NULL DEFAULT 'regular') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS shift_kasir (id INT AUTO_INCREMENT PRIMARY KEY,kasir_id INT NOT NULL,mulai DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,selesai DATETIME,saldo_awal INT NOT NULL DEFAULT 0,saldo_akhir INT,catatan TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
